// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJuUV0j0ZKgHGkqU7-mbqMXZp0s-bj8Wc',
    appId: '1:1054056680128:android:d31665c885bbde95d93b25',
    messagingSenderId: '1054056680128',
    projectId: 'laundry-flutter-app',
    storageBucket: 'laundry-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC13aVQOMw-XpDSWD56NKyQVECWYHd0bfQ',
    appId: '1:1054056680128:web:f982afcc621877a5d93b25',
    messagingSenderId: '1054056680128',
    projectId: 'laundry-flutter-app',
    authDomain: 'laundry-flutter-app.firebaseapp.com',
    storageBucket: 'laundry-flutter-app.firebasestorage.app',
    measurementId: 'G-VQWXG44NW1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtaeLUisMfKf9_VXRMRONE5chsutfCw84',
    appId: '1:1054056680128:ios:5aa24f934662c1a6d93b25',
    messagingSenderId: '1054056680128',
    projectId: 'laundry-flutter-app',
    storageBucket: 'laundry-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterLaundryApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtaeLUisMfKf9_VXRMRONE5chsutfCw84',
    appId: '1:1054056680128:ios:5aa24f934662c1a6d93b25',
    messagingSenderId: '1054056680128',
    projectId: 'laundry-flutter-app',
    storageBucket: 'laundry-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterLaundryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC13aVQOMw-XpDSWD56NKyQVECWYHd0bfQ',
    appId: '1:1054056680128:web:0b174dc962bdf197d93b25',
    messagingSenderId: '1054056680128',
    projectId: 'laundry-flutter-app',
    authDomain: 'laundry-flutter-app.firebaseapp.com',
    storageBucket: 'laundry-flutter-app.firebasestorage.app',
    measurementId: 'G-XZFYN2NZWR',
  );

}